version: 2.1

orbs:
  node: circleci/node@5

jobs:
  wakeup:
    docker:
      - image: circleci/node:16
    steps:
      - checkout
      - run:
          name: Wake up Strapi Server
          command: curl -s -o /dev/null -w "%{http_code}" https://kmuvcd-strapi.onrender.com

workflows:
  version: 2
  scheduled_wakeup:
    triggers:
      - schedule:
          cron: "2/5 * * * *"
          filters:
            branches:
              only: main
    jobs:
      - wakeup
