name: Run Scraper Every March

on:
  schedule:
    - cron: '48 3 * * *' # change it to 17 3 28 2 *
  workflow_dispatch:
    inputs:
      year:
        description: 'Enter the year to scrape events for (e.g., 2025)'
        required: false

jobs:
  scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: |
          if [ -z "${{ github.event.inputs.year }}" ]; then
            python scraper.py  # Use current year if no input is provided
          else
            python scraper.py ${{ github.event.inputs.year }}  # Use provided year
          fi

      - name: Check for file changes
        id: changed-files
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            echo "files_changed=true" >> $GITHUB_ENV
          fi

      - name: Commit and push changes
        if: env.files_changed == 'true'
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Update scraped data" || exit 0
          git push