name: Wake up Strapi Server

on:
  schedule:
  - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  wakeup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        node-version: '16'

    - name: Install Axios
      run: npm install axios

    - name: Run Wakeup Function
      run: |
          echo "Running wakeupStrapi function..."
          node -e "
            const axios = require('axios');
            async function wakeupStrapi() {
              try {
                await axios.get('https://kmuvcd-strapi.onrender.com');
              } catch (error) {
                console.error(\`Error in cyclic function: \${error.message}\`);
              }
            }
            wakeupStrapi();
          "
